export const authStyles = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, #f7efe2 0%, #eef5f2 100%)",
    padding: "2rem",
    fontFamily: "Arial, sans-serif",
  },
  card: {
    width: "100%",
    maxWidth: "460px",
    background: "#fff",
    borderRadius: "18px",
    boxShadow: "0 18px 40px rgba(29, 44, 46, 0.12)",
    padding: "2rem",
  },
  brand: {
    fontSize: "1.6rem",
    fontWeight: 700,
    color: "#1b3d36",
    marginBottom: "0.5rem",
    textDecoration: "none",
    display: "inline-block",
  },
  title: { margin: 0, fontSize: "2rem", color: "#1b2a2e" },
  subtitle: { margin: "0.5rem 0 1.5rem", color: "#5f686d" },
  form: { display: "flex", flexDirection: "column", gap: "1rem" },
  fieldGroup: { display: "flex", flexDirection: "column", gap: "0.4rem" },
  label: { fontSize: "0.9rem", fontWeight: 600, color: "#21333a" },
  input: {
    border: "1px solid #d8d2c6",
    borderRadius: "10px",
    padding: "0.85rem 0.9rem",
    fontSize: "1rem",
    outline: "none",
    background: "#fff",
  },
  checkboxRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: "0.7rem",
    color: "#4f5a5d",
    fontSize: "0.9rem",
    lineHeight: 1.5,
  },
  checkbox: { marginTop: "0.18rem" },
  error: { color: "#b42318", fontSize: "0.8rem", margin: 0 },
  banner: {
    background: "#fdecea",
    color: "#b42318",
    borderRadius: "10px",
    padding: "0.7rem 0.9rem",
    fontSize: "0.9rem",
  },
  hint: {
    background: "#eef5f2",
    color: "#1d5d52",
    borderRadius: "10px",
    padding: "0.7rem 0.9rem",
    fontSize: "0.85rem",
    marginBottom: "1rem",
  },
  button: {
    marginTop: "0.5rem",
    border: "none",
    borderRadius: "10px",
    background: "#1d5d52",
    color: "#fff",
    padding: "0.9rem 1rem",
    fontSize: "1rem",
    fontWeight: 700,
    cursor: "pointer",
  },
  secondaryButton: {
    marginTop: "0.75rem",
    border: "1px solid #d8d2c6",
    borderRadius: "10px",
    background: "#fff",
    color: "#2f3f44",
    padding: "0.8rem 1rem",
    fontSize: "0.95rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  footer: { marginTop: "1rem", color: "#56676d", textAlign: "center", fontSize: "0.95rem" },
  link: { color: "#1d5d52", fontWeight: 700, textDecoration: "none" },
};

export const divider = {
  display: "flex",
  alignItems: "center",
  gap: "0.8rem",
  margin: "1.2rem 0",
  color: "#8b9296",
  fontSize: "0.85rem",
};

export const dividerLine = { flex: 1, height: 1, background: "#e4ded1" };
